Add animator and stuff
Saviorium/platformer-framework pull request #5
Opened 2020-10-25 12:23 UTC by Saviorium

2020-10-25 12:32 UTC, Saviorium commented on game/dummy_animation_states.lua
> +        return AnimationState(
Слишком сложно, куча лишнего кода.
Надо бы упростить. Типа, по дефолту тупо переключаемся на тег и всё. И добавить в кондишен свойство "oneshot" - один раз воспроизводится и переключается. Или список дефолтных кондишенов.
И оставить, таки, возможность добавлять эти кастомные колбэки.
Возможно, добавить фабричный метод в аниматор, чтобы генерить AnimationState

2020-10-25 12:36 UTC, Saviorium commented on engine/animator.lua
> +        self._isLooped = false
🤔

2020-10-25 12:42 UTC, Saviorium commented on game/dummy_animation_states.lua
> +        return AnimationState(
Типа, сразу готовый стейт для 
"переключиться сразу"
"один раз проиграть и переключиться"
"чекнуть условие и переключиться когда анимация кончится"

2020-10-26 19:24 UTC, sawa9889 requested changes

2020-10-26 19:24 UTC, sawa9889 commented on engine/animator.lua
> +        self:addTransition(from, to, function() return condition and self:isLooped() end)
А тут кондишн не сработает если  убрать аниматора из стейта?

2020-10-26 19:24 UTC, sawa9889 commented on engine/animator.lua
> +    return self._isLooped
Нахуя геттер

2020-10-26 19:24 UTC, sawa9889 commented on engine/animator.lua
> +    self.variables[key] = value
Зачем сеттер в луа

2020-10-26 19:24 UTC, sawa9889 commented on engine/animator.lua
> +    return self.variables[key]
Чому?!

2020-10-26 19:24 UTC, sawa9889 commented on engine/animator.lua
> +    self.animation:draw(x, y, rot, sx, sy, ox, oy)
Доколе это будет доколе
Хотя ладно, тут можно логику центровки прилепить

2020-10-26 19:24 UTC, sawa9889 commented on engine/animator.lua
> +        transitionTo = self:_checkTransitions(self.transitions["*"])
Оно по умолчанию всегда создается?

2020-10-26 19:24 UTC, sawa9889 commented on engine/animator.lua
> +    if self.states[self.state] and self.states[self.state].onExit then
Почему ты постоянно проверяешь что стейт на котором ты просто есть в стейтах?

2020-10-26 19:24 UTC, sawa9889 commented on engine/animator.lua
> +    self._isLooped = false
Не должен ли этот признак быть не хранимым флагом а вычисляемым процедурой значением?

2020-10-26 19:24 UTC, sawa9889 commented on engine/animator.lua
> +    if Debug and Debug.PrintAnimationEvents then
Ты даже спрашиваешь есть ли дебаг....

2020-10-26 19:24 UTC, sawa9889 commented on game/dummy_animator.lua
> +            self:addState(state(self))
self:createSimpleTagState(Слово для названия, Слово для тега)
Чисто теоретически можно теги прям из файла доставать и под каждого из них стейт фигачить

2020-10-26 19:26 UTC, Saviorium commented on engine/animator.lua
> +    return self._isLooped
Тому что может тут какая-то логика будет. Или looped будет другое означать.
Что снаружи использует аниматор не будет знать реализации

2020-10-26 19:28 UTC, Saviorium commented on engine/animator.lua
> +        self:addTransition(from, to, function() return condition and self:isLooped() end)
Что?
Зачем его убирать из стейта?

2020-10-26 19:29 UTC, Saviorium commented on engine/animator.lua
> +    self.variables[key] = value
Чтобы не лезть во внутреннюю реализацию.
А то можно минуя аниматор прям из объекта тыкать как раньше. Вытащить наружу ссылку на все вариаблы и дёргать

2020-10-26 19:29 UTC, Saviorium commented on engine/animator.lua
> +    return self.variables[key]
См выше

2020-10-26 19:31 UTC, sawa9889 commented on engine/animator.lua
> +        self:addTransition(from, to, function() return condition and self:isLooped() end)
Я не предлагаю его убрать, я спрашиваю сработает ли функция как в плеере например на таймере работает, то есть в таймере нет каких-то параметров, с которыми функция оперирует, например можно сказать 
player.invincibility = false
И это сработает
Можно ли также функцию передать в стейт с параметрами вроде
Animator._isLoop() = false

2020-10-26 19:35 UTC, Saviorium commented on engine/animator.lua
> +    self.animation:draw(x, y, rot, sx, sy, ox, oy)
😒

2020-10-26 19:37 UTC, Saviorium commented on engine/animator.lua
> +        transitionTo = self:_checkTransitions(self.transitions["*"])
Нет. Но если ты добавил Transition от *, то он будет проверяться

2020-10-26 19:39 UTC, sawa9889 commented on engine/animator.lua
> +    if Debug and Debug.PrintAnimationEvents then
Ладно, это полезно если его нет, но может тогда его вовсе выкинуть?

2020-10-26 19:39 UTC, Saviorium commented on engine/animator.lua
> +    if self.states[self.state] and self.states[self.state].onExit then
Потому что npe
Ты можешь перейти на стейт которого нет
Ты можешь создать объект и не добавить стейт, но уже вызвать update

2020-10-26 19:40 UTC, sawa9889 commented on engine/animator.lua
> +        transitionTo = self:_checkTransitions(self.transitions["*"])
Если не будет self.transitions["*"] не сломается попытка взять его в pairs?

2020-10-26 19:40 UTC, Saviorium commented on engine/animator.lua
> +    self._isLooped = false
Потому что peachy вызывает onLoop один раз при зацикливании. Как ещё ты предлагаешь это делать?

2020-10-26 19:41 UTC, Saviorium commented on engine/animator.lua
> +    if Debug and Debug.PrintAnimationEvents then
Так везде надо. Чтобы можно было удалить дебаг и не умереть

2020-10-26 19:42 UTC, Saviorium commented on game/dummy_animator.lua
> +            self:addState(state(self))
Ок, если второе nil, тогда копипастим из первого

2020-10-26 19:46 UTC, Saviorium commented on engine/animator.lua
> +        self:addTransition(from, to, function() return condition and self:isLooped() end)
Стейт обращается к своему аниматору за переменными. Он может вызвать isLooped() на нём.

2020-10-26 19:46 UTC, sawa9889 commented on engine/animator.lua
> +    self.variables[key] = value
не вижу смысла в этом...
Только если мы не собираемся во что-то ещё это обернуть
Максимально зачем в иных либах делаются окологеттеры-сеттеы - это в векторе unpack который два значения через запятую просто достает

2020-10-26 19:46 UTC, sawa9889 commented on engine/animator.lua
> +    if self.states[self.state] and self.states[self.state].onExit then
Окей, апрувед

2020-10-26 19:46 UTC, sawa9889 commented on engine/animator.lua
> +    if self.states[self.state] and self.states[self.state].onExit then
Хотя я бы тогда лучше вместо 1000 npe карал за попытку сделать всё в обход нашего апи
Сделал что вот так всё работает и не ебет, кто там что сделал, если кто-то влез в нашу структуру бан ему npe-шкой
А делать структуру расчитывая что сам в неё можешь npe кидать это уж совсем больно

2020-10-26 19:56 UTC, sawa9889 commented on engine/animator.lua
> +    self._isLooped = false
isLooped - обозначение того что хоть раз анимация зациклилась

2020-10-26 19:58 UTC, sawa9889 commented on game/dummy_animator.lua
> +            self:addState(state(self))
Тогда почини)

2020-10-26 19:59 UTC, sawa9889 commented on game/dummy_animator.lua
> +            self:addState(state(self))
```suggestion
            self:createSimpleTagState(name, tag and tag or name)
```

2020-10-26 20:00 UTC, Saviorium commented on game/dummy_animator.lua
> +            self:addState(state(self))
no

2020-10-26 20:25 UTC, Saviorium commented on engine/animator.lua
> +    self.variables[key] = value
Ну хз, мне кажется, это хоть какой-то порядок внесёт

2020-10-26 21:21 UTC, Saviorium commented on engine/animator.lua
> +        self._isLooped = false
🤷

2020-10-26 21:23 UTC, sawa9889 approved these changes

2020-10-26 21:23 UTC, merged