Init map commit
Saviorium/platformer-framework pull request #6
Opened 2020-10-28 21:13 UTC by sawa9889

2020-11-06 22:38 UTC, Saviorium requested changes

2020-11-06 22:38 UTC, Saviorium commented on game/states/game.lua
> +    for _, object in ipairs(self.PhysicsProcessor.objects) do
Нет

2020-11-06 22:38 UTC, Saviorium commented on data/graphics/city_tileset.json
> +{ "frames": [
Не тащи все тайлсеты в движок

2020-11-06 22:38 UTC, Saviorium commented on engine/physics_processor.lua
> +    print(object)
Удоли потом все принты

2020-11-06 22:38 UTC, Saviorium commented on game/test_objects/map.lua
> +        priorityToDraw = priority and priority or 5,
priority = Nil тут

2020-11-06 22:38 UTC, Saviorium commented on game/test_objects/map.lua
> +function Map:addType(typeName, newType)
"Type" is ambiguous
ObjectType?

2020-11-06 22:38 UTC, Saviorium commented on game/test_objects/map.lua
> +    --     print(a.priorityToDraw, b.priorityToDraw)
Удали комменты или допили

2020-11-06 22:38 UTC, Saviorium commented on game/test_objects/map.lua
> +return function(params) return Map:loadParameters(params) end
Это мапа, которая держит одну мапу. Не менеджер, не контроллер. И она в /game/, а не в движке.
И ты можешь делать несколько раз init чтобы загружать разные карты. Тогда уж switch или load
А если я захочу 2 карты держать в игре одновременно?
А если я захочу разные парамс для каждой карты?

2020-11-06 22:38 UTC, Saviorium commented on main.lua
> +standartMapParams = require "game.test_objects.standart_map_params"
standar**d** пишется

2020-11-06 22:38 UTC, Saviorium commented on main.lua
>  Player = require "game.test_objects.player"
Почему не local то?

2021-04-18 20:56 UTC, sawa9889 commented on game/test_objects/map.lua
> +function Map:addType(typeName, newType)
Не понял

2021-06-16 20:00 UTC, closed without merging